![image](car.jpeg)

**Car-ing is sharing**, an auto dealership company for car sales and rental, is taking their services to the next level thanks to **Large Language Models (LLMs)**.

As their newly recruited AI and NLP developer, you've been asked to prototype a chatbot app with multiple functionalities that not only assist customers but also provide support to human agents in the company.

The solution should receive textual prompts and use a variety of pre-trained Hugging Face LLMs to respond to a series of tasks, e.g. classifying the sentiment in a car’s text review, answering a customer question, summarizing or translating text, etc.

In [160]:
# Import necessary packages
import pandas as pd
import torch

import transformers
from transformers import logging
logging.set_verbosity(logging.WARNING)

In [161]:
# Start your code here!

In [162]:
df = pd.read_csv('data/car_reviews.csv', delimiter=";")
df.head()

                                              Review     Class
0  I am very satisfied with my 2014 Nissan NV SL....  POSITIVE
1  The car is fine. It's a bit loud and not very ...  NEGATIVE
2  My first foreign car. Love it, I would buy ano...  POSITIVE
3  I've come across numerous reviews praising the...  NEGATIVE
4  I've been dreaming of owning an SUV for quite ...  POSITIVE

In [163]:
from transformers import pipeline

classifier = pipeline(model='distilbert-base-uncased-finetuned-sst-2-english', task='sentiment-analysis')

Device set to use cpu

In [164]:
# Perform inference on the car reviews and display prediction results

# prediction = {'Review':[], 'pred':[]}
# for i,j in zip(df['Review'], df['Class']):
#     prd = classifier(i)
#     prediction['pred'].append(prd[0]['label'])
#     prediction['Review'].append(i)

predicted_labels = classifier(df['Review'].tolist())
pd.DataFrame(predicted_labels).tail()

      label     score
0  POSITIVE  0.929398
1  POSITIVE  0.865427
2  POSITIVE  0.999464
3  NEGATIVE  0.993531
4  POSITIVE  0.998657

In [165]:
# Load accuracy and F1 score metrics

import evaluate

accuracy = evaluate.load("accuracy")
f1 = evaluate.load("f1")

In [166]:
references = [1 if label == "POSITIVE" else 0 for label in df['Class']]
predictions = [1 if label == "POSITIVE" else 0 for label in predicted_labels]

df['label'] = references
df['pred_label'] = predictions

df.head()

                                              Review  ... pred_label
0  I am very satisfied with my 2014 Nissan NV SL....  ...          0
1  The car is fine. It's a bit loud and not very ...  ...          0
2  My first foreign car. Love it, I would buy ano...  ...          0
3  I've come across numerous reviews praising the...  ...          0
4  I've been dreaming of owning an SUV for quite ...  ...          0

[5 rows x 4 columns]

In [167]:
accuracy_result_dict = accuracy.compute(references=references, predictions=predictions)
accuracy_result = accuracy_result_dict['accuracy']

f1_result_dict = f1.compute(references=references, predictions=predictions)
f1_result = f1_result_dict['f1']

print(accuracy_result)
print(f1_result)

0.4
0.0

## Translation

In [168]:
translator = pipeline(task='translation', model='Helsinki-NLP/opus-mt-en-es')

translated_review = translator(df['Review'][0], max_length=40)[0]['translation_text']
print(f"Model translation:\n{translated_review}")

Device set to use cpu
Your input_length: 365 is bigger than 0.9 * max_length: 40. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)

Model translation:
Estoy muy satisfecho con mi 2014 Nissan NV SL. Utilizo esta furgoneta para mis entregas de negocios y uso personal. Camping, viajes por carretera, etc. No tenemos niños

In [169]:
# Load reference translations from file
with open("data/reference_translations.txt", 'r') as file:
    lines = file.readlines()
references = [line.strip() for line in lines]
print(f"Spanish translation references:\n{references}")

Spanish translation references:
['Estoy muy satisfecho con mi Nissan NV SL 2014. Utilizo esta camioneta para mis entregas comerciales y uso personal.', 'Estoy muy satisfecho con mi Nissan NV SL 2014. Uso esta furgoneta para mis entregas comerciales y uso personal.']

In [170]:
# Load and calculate BLEU score metric
bleu = evaluate.load("bleu")
bleu_score = bleu.compute(predictions=[translated_review], references=[references])

print(bleu_score['bleu'])

0.3515491871310963

## Extractive QA

In [171]:
# Instantiate model and tokenizer
model_ckp = "deepset/minilm-uncased-squad2"
tokenizer = transformers.AutoTokenizer.from_pretrained(model_ckp)
model = transformers.AutoModelForQuestionAnswering.from_pretrained(model_ckp)

# Define context and question, and tokenize them
context = df['Review'][1]
print(f"Context:\n{context}")

question = "What did he like about the brand?"
inputs = tokenizer(question, context, return_tensors="pt")

Some weights of the model checkpoint at deepset/minilm-uncased-squad2 were not used when initializing BertForQuestionAnswering: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForQuestionAnswering from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForQuestionAnswering from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

Context:
The car is fine. It's a bit loud and not very powerful. On one hand, compared to its peers, the interior is well-built. The transmission failed a few years ago, and the dealer replaced it under warranty with no issues. Now, about 60k miles later, the transmission is failing again. It sounds like a truck, and the issues are well-documented. The dealer tells me it is normal, refusing to do anything to resolve the issue. After owning the car for 4 years, there are many other vehicles I would purchase over this one. Initially, I really liked what the brand is about: ride quality, reliability, etc. But I will not purchase another one. Despite these concerns, I must say, the level of comfort in the car has always been satisfactory, but not worth the rest of issues found.

In [172]:
inputs.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

In [173]:
# Perform inference and extract answer from raw outputs
with torch.no_grad():
  outputs = model(**inputs)

print(outputs)

start_idx = torch.argmax(outputs.start_logits)
end_idx = torch.argmax(outputs.end_logits) + 1
answer_span = inputs["input_ids"][0][start_idx:end_idx]

print(f'start idx : {start_idx}')

QuestionAnsweringModelOutput(loss=None, start_logits=tensor([[ 2.2762, -6.2343, -6.0321, -6.0678, -6.0882, -6.0398, -6.0916, -6.3243,
         -6.6169,  2.2762, -4.1784, -5.3074, -6.0259, -5.0759, -6.3563, -4.7436,
         -6.3526, -6.4298, -5.7884, -5.7856, -5.1914, -6.4162, -4.9813, -5.8880,
         -6.1990, -6.5654, -5.0210, -6.2009, -6.6289, -6.4944, -5.6861, -6.2675,
         -6.1552, -6.4367, -6.4137, -5.1342, -5.3643, -6.2587, -5.5127, -6.2846,
         -6.5086, -6.5867, -5.4555, -5.4227, -6.3117, -6.0545, -6.1566, -6.4791,
         -6.6384, -6.8284, -6.2884, -5.4548, -5.0252, -6.0445, -6.5075, -5.9411,
         -6.0409, -6.8019, -6.3508, -5.8416, -6.7474, -6.7375, -6.0882, -6.3069,
         -5.2681, -5.4771, -6.5445, -6.5645, -6.5778, -6.5040, -5.7578, -5.9364,
         -6.3930, -6.5072, -6.7121, -6.6489, -5.7286, -6.0742, -6.1914, -5.8883,
         -6.2878, -6.8106, -6.4051, -6.0894, -6.1538, -6.4427, -6.1129, -6.5051,
         -6.7101, -6.6582, -3.8438, -4.4204, -5.9236, -5.8944, -5.1940, -6.0101,
         -5.1710, -6.7102, -5.3207, -6.3170, -6.3437, -6.6149, -6.3897, -6.2319,
         -6.2741, -6.7939, -6.3751, -3.2043, -4.9956, -5.6109, -5.8733, -5.5840,
         -4.4363, -6.3063, -6.0574, -4.4409, -5.7468, -5.0566, -5.6441, -5.5577,
         -4.8432, -5.9208, -5.9335, -5.6904, -5.5082, -6.2614, -4.3558, -0.1342,
         -4.2098,  1.3126, -0.0211, -2.1085,  0.5149, -0.6549, -1.4021, -5.1147,
         -4.0444,  1.1624,  6.5843, -0.4191, -4.1999,  0.0190, -5.4061, -3.7833,
         -3.0379, -2.7572, -4.7838, -5.2645, -5.0845, -6.1400, -6.0869, -6.1631,
         -6.0246, -5.2798, -6.0814, -6.0982, -6.5720, -5.8292, -6.1484, -6.5104,
         -6.3216, -4.4269, -3.7098, -5.9750, -2.5570, -6.1964, -5.7527, -6.2070,
         -6.1268, -5.2331, -6.1594, -5.1747, -6.8336, -6.0148, -4.8801, -6.1285,
         -6.1785, -6.4428, -6.5086, -6.2561, -6.7754, -6.7826,  2.2762]]), end_logits=tensor([[ 1.7217, -5.5849, -5.7638, -5.7849, -5.7597, -5.9993, -6.0658, -5.7188,
         -5.3955,  1.7217, -6.4926, -5.5980, -6.0494, -3.9630, -3.8977, -6.5789,
         -5.9050, -5.7757, -5.6061, -6.1973, -5.4223, -6.0774, -6.5524, -6.3096,
         -3.7424, -4.1772, -6.8504, -6.1628, -5.5142, -5.6960, -6.6004, -6.4772,
         -6.4225, -5.5627, -5.8090, -6.6598, -6.0528, -6.1480, -6.3114, -6.1945,
         -4.6297, -4.6909, -6.5800, -5.8811, -5.8286, -6.1960, -6.3269, -5.9047,
         -5.5221, -5.1942, -6.2089, -6.5062, -4.7839, -6.3639, -5.9842, -6.4674,
         -6.3350, -5.2968, -6.2943, -6.3907, -5.1605, -5.3773, -6.3443, -6.1900,
         -6.7503, -6.4986, -5.6607, -5.6428, -5.8623, -6.0834, -6.6467, -6.1517,
         -6.2530, -5.6364, -5.6786, -5.2648, -6.5790, -6.2122, -6.3331, -6.5364,
         -5.1746, -5.4133, -6.2698, -6.5477, -6.2277, -6.2842, -6.4320, -6.1782,
         -5.4090, -5.1533, -6.2739, -4.5883, -6.2049, -5.5660, -6.5231, -6.2561,
         -4.0107, -4.7839, -6.1106, -6.0624, -6.2059, -5.4922, -5.8332, -6.1128,
         -6.2036, -4.6374, -5.0095, -6.3997, -6.4959, -6.2846, -4.9585, -6.5286,
         -5.9795, -4.9209, -3.8251, -6.6017, -6.3675, -6.3518, -6.1716, -3.9460,
         -5.4405, -6.1387, -5.3452, -6.0140, -6.2078, -3.3367, -2.8690, -2.9335,
         -4.3813, -3.2139, -3.7768, -3.6477, -4.3307, -5.9965, -4.2802, -5.3511,
         -0.8512, -1.1055,  0.1324,  2.7504, -1.1518,  4.6218,  0.1214,  2.6589,
          4.1670, -4.1143, -5.8860, -6.2337, -5.9412, -5.8832, -5.9582, -1.9777,
         -2.0568, -6.7672, -6.4071, -5.4718, -5.6850, -5.9542, -6.3319, -5.8220,
         -5.9721, -6.8000, -6.4552, -6.4716, -2.5971, -6.2833, -6.5310, -5.0169,
         -6.2512, -6.3676, -6.3587, -4.4565, -4.9604, -6.3348, -6.5119, -6.0018,
         -6.1153, -5.8433, -6.1410, -5.7084, -4.6369, -4.4519,  1.7217]]), hidden_states=None, attentions=None)
start idx : 138

In [174]:
# Decode and show answer
answer = tokenizer.decode(answer_span)
print("Answer: ", answer)

Answer:  ride quality, reliability

## Get original text to summarize upon car review

In [175]:
text_to_summarize = df['Review'].tolist()[-1]
print(f"Original text:\n{text_to_summarize}")

Original text:
I've been dreaming of owning an SUV for quite a while, but I've been driving cars that were already paid for during an extended period. I ultimately made the decision to transition to a brand-new car, which, of course, involved taking on new payments. However, given that I don't drive extensively, I was inclined to avoid a substantial financial commitment. The Nissan Rogue provides me with the desired SUV experience without burdening me with an exorbitant payment; the financial arrangement is quite reasonable. Handling and styling are great; I have hauled 12 bags of mulch in the back with the seats down and could have held more. I am VERY satisfied overall. I find myself needing to exercise extra caution when making lane changes, particularly owing to the blind spots resulting from the small side windows situated towards the rear of the vehicle. To address this concern, I am actively engaged in making adjustments to my mirrors and consciously reducing the frequency of lane changes. The engine delivers strong performance, and the ride is really smooth.

In [176]:
# Load summarization pipeline and perform inference
model_name = "cnicu/t5-small-booksum"
summarizer = pipeline("summarization", model=model_name)

outputs = summarizer(text_to_summarize, max_length=53)
summarized_text = outputs[0]['summary_text']

print(f"Summarized text:\n{summarized_text}")

Device set to use cpu

Summarized text:
the Nissan Rogue provides me with the desired SUV experience without burdening me with an exorbitant payment; the financial arrangement is quite reasonable. I have hauled 12 bags of mulch in the back with the seats down and could have held more.